#MODELS
MODEL_PREDEFINED_PRODUCT_NAME_LENGTH = 100
MODEL_CATEGORY_NAME_LENGTH = 80
MODEL_UNIT_NAME_LENGTH = 8
MODEL_PRODUCT_MAX_QUANTITY = 10000
MODEL_PRODUCT_MIN_QUANTITY = 1
MODEL_PRODUCT_MAX_COMMENT = 200
MODEL_PRODUCT_MAX_LINK = 200
MODEL_RECIPE_LINK_LENGTH = 200
LOGIN_URL = '/shoppinglist/login/'